### ISSUE TITLE
Tag Flowershow v1

### ISSUE THREAD

**Issue by rufuspollock** [datopian/flowershow#482]
We have a solid stable Flowershow "v1" and have since monorepo work in Jan.

We are about to do major changes e.g. #465 and this will be Flowershow v2.

Want to tag and release v1.

## Acceptance

- [ ] Tag a v1 with the monorepo in Jan ... and subsequent development

**Comment by olayway** [comment]
Flowershow template has been tagged with 1.x.x versions since March. We have also just created a special branch - `v1` - as an archive for the monorepo version with Flowershow template using Contentlayer. Flowershow template on the current `main` branch is now using our own content layer solution - @flowershow/markdowndb, and has been tagged `@flowershow/template@2.0.0` since the switch.
