### ISSUE TITLE
multiline formula support

### ISSUE THREAD

**Issue by miptctx** [datopian/flowershow#556]
Latex has `multline` option to render formulas on few lines. Obsidian also support this option but flowershow doesn't. For example, this works in obsidian:
```latex
$$
\begin{multline}
some\ very\ very\ very\ very\ very\ very\ very\ very\ very\ very\ very\ very\ \\
very\ very\ very\ very\ very\ very\ very\ very\ long\ formula
b=c
\end{multline}
$$
```

And obsidian will draw such view:
![image](https://github.com/datopian/flowershow/assets/116687919/7a126e19-04ea-4fbc-a737-a45205be9b5a)

But flowershow will not process this option correctly and it will make such view:
![image](https://github.com/datopian/flowershow/assets/116687919/8f5a8a6c-60c2-4711-8cb7-cfa4512575cf)

At the same time the `split` options works in flowershow, but this option does not render formula such perfect line `multline` does:
```latex
$$
\begin{multline}
some\ very\ very\ very\ very\ very\ very\ very\ very\ very\ very\ very\ very\ \\
very\ very\ very\ very\ very\ very\ very\ very\ long\ formula
b=c
\end{multline}
$$
```

This will give such view in flowershow:
![image](https://github.com/datopian/flowershow/assets/116687919/1233fe09-ff9b-4509-8eb2-cc31a549915a)

Is it possible to add `multline` support?

Thanks.

**Comment by olayway** [comment]
@miptctx Thank you for reporting this issue! I'll look into it!

**Comment by olayway** [comment]
@miptctx Unfortunately, it's not possible to add support for it. Flowershow uses KaTeX library to render LaTeX in the browser, and while it's primarily designed for LaTeX it doesn't support all the LaTeX syntax due to it's focus on performance.

But thank you so much for flagging this! Thanks to you, I realized the equations weren't even styled properly as I forgot to import KaTeX styles 🤦‍♀️.
