### ISSUE TITLE
The publish-tutorial page leads to a 404

### ISSUE THREAD

**Issue by BiosPlus** [datopian/flowershow#575]
https://flowershow.app/docs/publish-tutorial

![image](https://github.com/datopian/flowershow/assets/9003059/51dd64ab-ff5c-4a78-a7f2-1c5b40de0126)

**Comment by rufuspollock** [comment]
Hmmm, thanks for reporting. I've identified the issue is that this page was deprecated in favour of https://flowershow.app/docs/publish-howto

However would be better to still have the page there with a deprecation notice: so will look into that.

BTW how did you find this page (via google or a link or the site?)

**Comment by rufuspollock** [comment]
FIXED. Reinstated page with deprecation notice. https://flowershow.app/docs/publish-tutorial

**Comment by BiosPlus** [comment]
Apologies for the lack of response. 
I can't recall wherein the page was referenced on the site originally, It was during some aggressive opening of every link I could find to get started haha. But thank you for actioning @rufuspollock ❤️
